version: '3.4'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "nininhatico1#"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data
  gbstoreapi.webapi:
    image: ${DOCKER_REGISTRY-}gbstoreapiwebapi
    env_file: 
    - path: .env
      required: true
    build:
      context: .
      dockerfile: GbStoreApi.WebApi/Dockerfile
    environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "nininhatico1#"
      Database: "GbStoreDatabase"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    ports: 
      - "443:443"